MAX_ORDER_VALUE = 100000 # Max ₹1 Lakh per trade
RESTRICTED_SYMBOLS = ["PENNYSTOCK1", "ILLIQUID2"]

def validate_order(order_dict: dict) -> dict:
    """
    Acts as a bouncer. If the AI hallucinates, this stops the trade.
    Raises ValueError if risk parameters are breached.
    """
    symbol = order_dict.get("symbol")
    qty = order_dict.get("qty", 0)
    
    if symbol in RESTRICTED_SYMBOLS:
        raise ValueError(f"AI attempted to trade restricted symbol: {symbol}")
        
    if qty <= 0:
        raise ValueError("Invalid quantity generated by AI.")
        
    # TODO: Calculate estimated margin against MAX_ORDER_VALUE
    
    # If all checks pass:
    return order_dict
